import { Game } from "@/models/game";

export const initialGames: Game[] = [
  {
    id: "1",
    sport: "Soccer",
    teamA: "Liverpool",
    teamB: "Manchester United",
    oddsA: 2.1,
    oddsB: 1.8,
    betsA: 120,
    betsB: 150,
  },
  {
    id: "2",
    sport: "Basketball",
    teamA: "Lakers",
    teamB: "Celtics",
    oddsA: 1.9,
    oddsB: 2.0,
    betsA: 200,
    betsB: 180,
  },
  {
    id: "3",
    sport: "Basketball",
    teamA: "Yankees",
    teamB: "Red Sox",
    oddsA: 1.7,
    oddsB: 2.2,
    betsA: 150,
    betsB: 100,
  },
  {
    id: "4",
    sport: "Soccer",
    teamA: "Barcelona",
    teamB: "Real Madrid",
    oddsA: 2.5,
    oddsB: 1.9,
    betsA: 250,
    betsB: 220,
  },
  {
    id: "5",
    sport: "Tennis",
    teamA: "Nadal",
    teamB: "Federer",
    oddsA: 1.8,
    oddsB: 2.1,
    betsA: 300,
    betsB: 280,
  },
  {
    id: "6",
    sport: "Soccer",
    teamA: "India",
    teamB: "Australia",
    oddsA: 2.0,
    oddsB: 1.9,
    betsA: 180,
    betsB: 200,
  },
  {
    id: "7",
    sport: "Rugby",
    teamA: "Toronto Maple Leafs",
    teamB: "Montreal Canadiens",
    oddsA: 2.2,
    oddsB: 1.7,
    betsA: 140,
    betsB: 160,
  },
  {
    id: "8",
    sport: "Rugby",
    teamA: "New Zealand",
    teamB: "South Africa",
    oddsA: 1.9,
    oddsB: 2.0,
    betsA: 220,
    betsB: 210,
  },
  {
    id: "9",
    sport: "Boxing",
    teamA: "Tyson Fury",
    teamB: "Anthony Joshua",
    oddsA: 1.6,
    oddsB: 2.3,
    betsA: 350,
    betsB: 320,
  },
  {
    id: "10",
    sport: "Soccer",
    teamA: "Patriots",
    teamB: "Packers",
    oddsA: 2.3,
    oddsB: 1.9,
    betsA: 400,
    betsB: 370,
  },
];